#pragma once

#include "aiguard/common/event.h"
#include "aiguard/engine/event_windows.h"
#include <string>
#include <vector>
#include <memory>
#include <unordered_map>
#include <mutex>
#include <functional>
#include <atomic>
#include <chrono>
#include <regex>
#include <shared_mutex>

namespace aiguard {

/// Correlation rule condition
struct Condition {
    std::string field;      // Event field to match
    std::string op;         // =, !=, contains, regex, >, <, >=, <=
    std::string value;      // Value to compare against
    std::shared_ptr<std::regex> compiled_regex; // Cached compiled regex
};

/// Correlation rule - defines a pattern of events that constitute a threat
struct CorrelationRule {
    std::string id;
    std::string name;
    std::string description;
    std::string mitre_tactic;      // MITRE ATT&CK tactic
    std::string mitre_technique;   // MITRE ATT&CK technique
    Severity severity{Severity::Medium};
    uint8_t severity_score{50};

    // Conditions for matching events
    std::vector<Condition> conditions;

    // Time window for correlation (milliseconds)
    int64_t time_window_ms{60000};

    // Minimum number of matching events to trigger
    uint32_t threshold{1};

    // Aggregation field (group events by this field)
    std::string aggregation_field;

    // Action to take when rule fires
    std::string action;     // alert, isolate, block, etc.

    // Optional: reference to Sigma rule
    std::string sigma_rule_id;
};

/// Alert generated by correlation
struct Alert {
    std::string id;
    std::string rule_id;
    std::string rule_name;
    std::string description;
    std::string mitre_tactic;
    std::string mitre_technique;
    Severity severity{Severity::Medium};
    uint8_t severity_score{50};
    std::chrono::system_clock::time_point timestamp;
    std::vector<Event> triggering_events;
    std::string aggregation_key;
    uint32_t match_count{0};
    std::string action;
    std::string status{"open"};  // open, acknowledged, resolved
};

/// Correlation engine - matches events against rules
///
/// Features:
/// - Real-time event matching against multiple rules
/// - Time-windowed correlation
/// - Threshold-based alerting
/// - Aggregation by field
/// - SIMD-optimized condition matching (AVX-512)
class CorrelationEngine {
public:
    CorrelationEngine();
    ~CorrelationEngine() = default;

    /// Add a correlation rule
    void add_rule(std::unique_ptr<CorrelationRule> rule);

    /// Remove a rule by ID
    bool remove_rule(const std::string& rule_id);

    /// Process an event against all rules
    /// @return Vector of alerts generated
    std::vector<Alert> process_event(const Event& event);

    /// Process a batch of events
    std::vector<Alert> process_events(const std::vector<std::unique_ptr<Event>>& events);

    /// Get all registered rules
    std::vector<const CorrelationRule*> get_rules() const;

    /// Get rule count
    [[nodiscard]] size_t rule_count() const;

    /// Clear expired correlation state
    void cleanup_expired();

    /// Correlation statistics
    struct Stats {
        uint64_t events_processed{0};
        uint64_t alerts_generated{0};
        uint64_t rules_matched{0};
        uint64_t rules_evaluated{0};
    };
    [[nodiscard]] Stats get_stats() const;

private:
    /// Check if an event matches a rule's conditions
    bool matches_conditions(const Event& event, const CorrelationRule& rule) const;

    /// Check a single condition
    bool check_condition(const Event& event, const Condition& cond) const;

    /// SIMD-optimized string comparison (AVX-512)
    bool simd_string_compare(const std::string& a, const std::string& b, const std::string& op) const;

    /// Extract field value from event as string
    std::string get_field_string(const Event& event, const std::string& field) const;

    // Rule storage
    std::unordered_map<std::string, std::unique_ptr<CorrelationRule>> rules_;
    mutable std::shared_mutex rules_mutex_;

    // Correlation state: rule_id -> aggregation_key -> [timestamps]
    struct CorrelationState {
        std::chrono::system_clock::time_point first_seen;
        std::chrono::system_clock::time_point last_seen;
        std::vector<std::chrono::system_clock::time_point> timestamps;
        std::vector<Event> events;
    };
    std::unordered_map<std::string, std::unordered_map<std::string, CorrelationState>> state_;
    mutable std::mutex state_mutex_;

    Stats stats_;
    mutable std::mutex stats_mutex_;
};

} // namespace aiguard
